# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "IntraBox"

# ldap server address
ldapserver: "ldap.enstimac.fr"

# Alias for send message
mailApp: "no_reply@Intrabox.com"

# Path of Upload Files
pathUpload: "/Program Files (x86)/Apache Software Foundation/Apache2.2/cgi-bin/IntraBox/public/Upload"

# Path of Download Files (relative to fileController)
pathDownload: "/Upload"

# Path of Application
pathApp: "http://localhost/cgi-bin/IntraBox/public/dispatch.cgi"

# Limit rule for group creation
# Maximum of expiration days for deposit
maxExpirationDays: 365
# Maximum size for personnal account in bytes (now : 5 Go)
maxQuota: 5368709120

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

session: "simple"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
    plugin:

plugins:
    DBIC:
      DbIntraBox:
        schema_class: DB::intrabox
        dsn: dbi:mysql:intrabox
        user: root
        pass: Musique12
        options:
          RaiseError: 1
          PrintError: 1
          mysql_enable_utf8: 1
    Email:
      driver: smtp
      host: smtp.mines-albi.fr

